title: Gifootball | 姐夫足球网
description: 足球纪念馆
baseurl:
permalink: /:categories/:year/:month/:day/:title.html
paginate: 9
paginate_path: /page/:num/
infinite_scroll: true #change to false if you want to use pagination
plugins: [jekyll-paginate]
tag_dir: /tag
category_dir: /category
category_layout: index.html

encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
# relative_permalinks: false
tucao: 40428
exclude: [.git, .gitignore, package.json, node_modules, README.md, _site]
