title: gifootball
description: 足球纪念馆
baseurl: /
permalink: /:categories/:year-:month-:day/:title.html
paginate: 9
paginate_path: /page/:num/
infinite_scroll: true #change to false if you want to use pagination
plugins: [jekyll-paginate]

encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
# relative_permalinks: false
tucao: 40428
exclude: [.git, .gitignore, package.json, node_modules, _site,docker-compose.yml,Gemfile]

youku_client_id: 152011440e2ee7ef
valine_app_id: e9wJgylSvjTXzbxHOVjbKP6e-gzGzoHsz
valine_app_key: KSS08hLw9AkuKzSYC7PV1B88
baidu_analysis: fbaddcdc614ca0725679f169efb480a5
google_analysis: UA-129341547-1
pic_bed_root: http://p.ananas.chaoxing.com/star3/origin/
pic_bed_featimg_root: http://pan-yz.chaoxing.com/thumbnail/400,160,50/
static_cdn_root: //cdn.jsdelivr.net/gh/Valdanitooooo/gifootball
